# Generated by Django 3.2.2 on 2021-05-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('kks', models.CharField(max_length=20, verbose_name='KKS-код здания')),
                ('name', models.CharField(max_length=200, verbose_name='Официальное точное название')),
            ],
            options={
                'ordering': ['kks'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Имя проекта')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('stage', models.CharField(max_length=10, verbose_name='Текущая стадия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('kks', models.CharField(max_length=20, unique=True, verbose_name='KKS-код системы')),
                ('name', models.CharField(max_length=200, verbose_name='Точное название системы')),
                ('seismic_category', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('NA', 'Not specified')], max_length=3)),
                ('safety_category', models.CharField(choices=[('1', 'First class'), ('2', 'Second class'), ('3', 'Third class'), ('4', 'Fourth class'), ('EYT', 'EYT'), ('NA', 'Not specified')], max_length=3)),
                ('buildings', models.ManyToManyField(related_name='systems', to='AtomproektBase.Building', verbose_name='Перечень зданий, в которых находится система')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='AtomproektBase.project', verbose_name='Проект, которому принадлежит система')),
            ],
            options={
                'ordering': ['kks'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='AtomproektBase.project', verbose_name='Проект, которому принадлежит здание'),
        ),
    ]
