# Generated by Django 3.2.2 on 2021-06-02 07:45

import EasyView.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AtomproektBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nwd', models.FileField(blank=True, null=True, upload_to=EasyView.models.get_upload_path, verbose_name='Модель здания (формат .nwd)')),
                ('gltf', models.FileField(blank=True, null=True, upload_to=EasyView.models.get_upload_path, verbose_name='Модель здания (формат .gltf или .glb)')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='AtomproektBase.building', verbose_name='Здание')),
            ],
        ),
        migrations.CreateModel(
            name='ViewPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3)),
                ('quaternion', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4)),
                ('distance_to_target', models.FloatField(blank=True, null=True)),
                ('clip_constants', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=6)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_points', to='EasyView.model3d')),
            ],
            options={
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=3)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='EasyView.model3d')),
                ('view_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_notes', to='EasyView.viewpoint')),
            ],
            options={
                'ordering': ['-creation_time'],
            },
        ),
    ]
