# Generated by Django 3.2.2 on 2021-06-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='model',
        ),
    ]
