# Generated by Django 3.2.2 on 2021-06-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyView', '0002_remove_note_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='view_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='EasyView.viewpoint'),
        ),
    ]
