# Generated by Django 3.2.2 on 2021-06-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyView', '0003_alter_note_view_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('speciality', models.CharField(choices=[('Process', 'Технология'), ('Electrical', 'Электрика'), ('HVAC', 'Вентиляция')], max_length=11)),
                ('reviewer', models.CharField(max_length=100)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('Uncompleted', 'Не выполнено'), ('Completed', 'Выполнено')], default=('Uncompleted', 'Не выполнено'), max_length=11)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('view_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='EasyView.viewpoint')),
            ],
            options={
                'ordering': ['-creation_time'],
            },
        ),
    ]
