# Generated by Django 3.2.2 on 2021-06-13 20:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyView', '0004_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpoint',
            name='nw_quaternion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=4),
            preserve_default=False,
        ),
    ]
