# Generated by Django 3.2.2 on 2021-06-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyView', '0005_viewpoint_nw_quaternion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewpoint',
            name='nw_quaternion',
        ),
    ]
