# Generated by Django 3.2.2 on 2021-06-16 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyView', '0006_remove_viewpoint_nw_quaternion'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpoint',
            name='clip_constants_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=[False, False, False, False, False, False], size=6),
        ),
    ]
