# Generated by Django 3.2.2 on 2021-06-29 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyView', '0007_viewpoint_clip_constants_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpoint',
            name='fov',
            field=models.FloatField(blank=True, default=60.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
