# Generated by Django 3.2.2 on 2021-07-14 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyView', '0010_alter_remark_view_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpoint',
            name='fov',
            field=models.FloatField(blank=True, default=60.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(179)]),
        ),
    ]
